basePath: /
host: 34.212.84.161
info:
  contact: {}
  title: NFTime Sample Swagger API
  version: "1.0"
paths:
  /getNFTInfoWithId:
    get:
      consumes:
      - application/json
      description: Get nft info
      parameters:
      - description: nft_id
        in: query
        name: nft_id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: NFT
      tags:
      - NFT
  /works:
    get:
      consumes:
      - application/json
      description: Get works
      parameters:
      - description: name
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: NFT
swagger: "2.0"
