basePath: /
host: localhost:80
info:
  contact: {}
  title: NFTime Sample Swagger API
  version: "1.0"
paths:
  /getNFTInfoWithId:
    get:
      consumes:
      - application/json
      description: Get nft info
      parameters:
      - description: nft_id
        in: query
        name: nft_id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get specific NFT
      tags:
      - NFT
  /like:
    post:
      consumes:
      - application/json
      description: update like
      parameters:
      - description: id of user
        in: body
        name: UserId
        required: true
        schema:
          type: string
      - description: id of work
        in: body
        name: WorkId
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses: {}
      summary: update like
      tags:
      - Like
  /work/specific:
    get:
      consumes:
      - application/json
      description: Get works
      parameters:
      - description: name
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: get specific work
      tags:
      - Work
  /work/top10:
    get:
      consumes:
      - application/json
      description: get top 10 works
      produces:
      - application/json
      responses: {}
      summary: get top 10 works
      tags:
      - Work
swagger: "2.0"
